### ISSUE TITLE
IndexOutOfRangeException while running with code coverage

### ISSUE THREAD

**Issue by overeemm** [mmanela/chutzpah#335]
I'm seeing this Exception during automated build (TFS build) with code coverage enabled:

    Error: System.IndexOutOfRangeException: Index was outside the bounds of the array.
       at System.Collections.Generic.List`1.Add(T item)
       at Chutzpah.Coverage.BlanketJsCoverageEngine.AddExcludePatterns(IEnumerable`1 patterns)
       at Chutzpah.TestContextBuilder.GetConfiguredCoverageEngine(TestOptions options, ChutzpahTestSettingsFile chutzpahTestSettings)
       at Chutzpah.TestContextBuilder.SetupCodeCoverageEngine(TestOptions options, ChutzpahTestSettingsFile chutzpahTestSettings, IFrameworkDefinition definition, List`1 referencedFiles)
       at Chutzpah.TestContextBuilder.BuildContext(PathInfo file, TestOptions options)
       at Chutzpah.TestContextBuilder.TryBuildContext(PathInfo file, TestOptions options, TestContext& context)
       at Chutzpah.TestRunner.<>c__DisplayClass7.<BuildTestContexts>b__6(PathInfo testFile)

According to .NET this comes from concurrent access to the lists. But I have never seen this issue. What could be the cause?

**Comment by overeemm** [comment]
Hmmm. Another build and that one succeeded. So it is not in the settings. Is this a concurrency bug that happens now and then?

**Comment by mmanela** [comment]
Thanks for reporting this. It does look like there is a real concurrency issue. Surprised that it has took this long to turn up. I will fix for the next release

**Comment by mmanela** [comment]
I committed a fix for this, I will mark as closed but once the 4.0 release is available please try to validate.

**Comment by alaney** [comment]
My team has been using Chutzpah for a few months now an we saw this error intermittently in TFS builds and when running coverage locally in VS. I hoped that it would be resolved in 4.0 but I just updated my VS extension and I still get it when trying to run coverage. Haven't tried it on a TFS build yet. How can I help resolve the issue

**Comment by mmanela** [comment]
Thanks, I saw the issue in my original fix.

**Comment by overeemm** [comment]
We are running with the 4.0.1 version, and are not seeing the problem anymore. As far as we can tell, the bug is fixed.
