### ISSUE TITLE
"error loading source script" when running chutzpah, only with codecoverage and trace enabled

### ISSUE THREAD

**Issue by GoeniGoeGoe** [mmanela/chutzpah#340]
I'm trying to use chutzpah to execute JS tests and calculate coverage, via the command line runner, in Visual Studio and in TFS build. These all throw an error, even though the coverage html file is generated. 

The error I get in all cases is:
"Error: Error: error loading source script
in file:///e:/src/F/Dev/######/####/###/Src/packages/Chutzpah.3.3.1/tools/TestFil
es/Coverage/blanket_jasmine_v2.js (line 5141)
While Running:E:\src\F\Dev\######\####\###\Src\##########\Tests\#####.##########.
###.###.Notification.UI.Test\Javascript\SewNotificationRuleEditSpec.js"

The strange thing is that I only get this error from the command line runner and Visual Studio when I enable tracing (with the /trace switch or in VS options).

In TFS the error is always thrown, which fails my build.

**Comment by mmanela** [comment]
Can you provide a repro?

**Comment by GoeniGoeGoe** [comment]
Hi, I was hoping you could provide some pointers to debug this. I just noticed that I am currently only able to reproduce it consistently in Visual Studio and TFS. The command line runner fails intermittently, not sure why. I will make sure to make a repro available.

**Comment by GoeniGoeGoe** [comment]
I'm absolutely new to Git, but I think I've made the repro available here: https://github.com/GoeniGoeGoe/ChutzpahRepro

**Comment by mmanela** [comment]
I am unable to reproduce your issue with the sample you provided. I tried running with both coverage and trace from VS and from the command line and it worked fine in both.

**Comment by alaney** [comment]
I also see this error with almost every TFS build but never in VS. Just updated to Chutzpah 4.0 in VS and on my Build Machine but it is still present. This particular issue was very rare until our test count reached about 300.

**Comment by mmanela** [comment]
Can you provide me with a repro?

**Comment by alaney** [comment]
This seems to have been resolved for the time being I updated our .config file from

**Comment by alaney** [comment]
This seems to have been resolved for the time being. I updated our .config file from
```javascript
{ "RootReferencePathMode": "SettingsFileDirectory",
    "References": [{ "Path": "libs/jasmine.js" },
        { "Path": "libs/common.js" },
        { "Path": "../../../../../Scripts/libs/jquery/jquery-1.10.2.min.js" },
        { "Path": "../../../../../Scripts/libs/angularjs/angular.js" },
        { "Path": "../../../../../Scripts/libs/angularjs/angular-touch.js" },
        { "Path": "../../../../../Scripts/libs/angularjs/angular-mocks.js" },
        { "Path": "../../../../../Scripts/libs/kendo/2014.3.1316/kendo.all.min.js" },
        { "Path": "../../../../../Scripts/libs/d3/d3.js" },
        { "Path": "../../../../../Scripts/libs/ngsortable/ngsortable.js" },
        { "Path": "../../../../../Scripts/libs/toastr/toastr.js" },
        { "Path": "../../../../../Scripts/libs/uirouter/ui-router.js" },
        { "Path": "../../../../../Scripts/SPEnterprisePortal" }],
    "CodeCoverageExcludes": [ "*references.js", "*.spec.js"],
    "CodeCoverageIncludes": ["**Ctrl.js","**Svc.js","**Dir.js","**Dec.js"],
    "Tests": [{ "Include": "*.spec.js" }],
    "CustomTestHarnessPath": "../CustomTestHarness.html"
}
```

==================TO===================
```javascript
{"Framework": "jasmine",
	"RootReferencePathMode": "SettingsFileDirectory",
    "References": [{ "Path": "../../../../../Scripts/libs/jquery/jquery-1.10.2.min.js", "IsTestFrameworkFile": true },
        { "Path": "../../../../../Scripts/libs/angularjs/angular.js", "IsTestFrameworkFile": true },
        { "Path": "../../../../../Scripts/libs/angularjs/angular-touch.js", "IsTestFrameworkFile": true },
        { "Path": "../../../../../Scripts/libs/angularjs/angular-mocks.js", "IsTestFrameworkFile": true },
        { "Path": "../../../../../Scripts/libs/kendo/2014.3.1316/kendo.all.min.js", "IsTestFrameworkFile": true },
        { "Path": "../../../../../Scripts/libs/d3/d3.js", "IsTestFrameworkFile": true },
        { "Path": "../../../../../Scripts/libs/ngsortable/ngsortable.js", "IsTestFrameworkFile": true },
        { "Path": "../../../../../Scripts/libs/toastr/toastr.js", "IsTestFrameworkFile": true },
        { "Path": "../../../../../Scripts/libs/uirouter/ui-router.js", "IsTestFrameworkFile": true },
        { "Path": "../../../../../Scripts/SPEnterprisePortal", "Includes": [ "*.js" ] },
        { "Path": "libs/common.js" }],
    "IgnoreResourceLoadingErrors": true,
    "CodeCoverageExcludes": ["*references.js", "*.spec.js"],
    "CodeCoverageIncludes": ["**Ctrl.js","**Svc.js","**Dir.js","**Dec.js"],
    "Tests": [{ "Path": "specs", "Include": "*.spec.js" }],
    "CustomTestHarnessPath": "../CustomTestHarness.html"
}
```
Not sure what may have been causing this.

**Comment by GoeniGoeGoe** [comment]
The issue was also fixed for me by setting "IsTestFrameworkFile": true on the references that we do not want to include in the coverage. I first checked Chutzpah 4.0 and the "IgnoreResourceLoadingErrors" property, but this did not fix the issue.

**Comment by alaney** [comment]
Looks like this reduced the frequency of the error but I still see it in TFS builds from time to time.

**Comment by mmanela** [comment]
Can you please provide a repro?

**Comment by jimithing277** [comment]
I too was having the same issue and corrected it by adding "IsTestFrameworkFile": "true" to all of our references.  It seems the issue is that the jasmine_blanket script include needs to be added last.  By setting "IsTestFrameworkFile": "true" on all our references it essentially accomplished this.

**Comment by mmanela** [comment]
Closing issue. Original poster can re-open if not fixed.

**Comment by Karankang007** [comment]
This is reproducible for me in 4.1.0 build.

**Comment by mmanela** [comment]
Can you please provide a full repro that I can download and run?

**Comment by T-rav** [comment]
I have created a new ticket for this issue @ https://github.com/mmanela/chutzpah/issues/493. It details how I fixed it.
