### ISSUE TITLE
Can we stop the web page being opened after running tests?

### ISSUE THREAD

**Issue by MrYossu** [mmanela/chutzpah#661]
I use the VS extension for Chutzpah, so can see and run my tests in the Unit Test Sessions window in VS. I don't need the web page that pops up every time you run the tests, and it's pretty annoying to have to close it each time.

Any way we can prevent this web page popping up?

Thanks

P.S. This is NOT a criticism of Chutzpah by the way! Chutzpah is excellent, I just don't want this web page :)

**Comment by mmanela** [comment]
What are your setting in the chutzpah.json file, by default nothing should be popping up.

**Comment by mmanela** [comment]
Can you give a minimal repro of the issue that I can run locally?

**Comment by MrYossu** [comment]
Will have to wait until next week, as I'm on holiday, so not able to access my work computer (where the files are stored). Will try and get something run up for you then.

Thanks

**Comment by PandaWood** [comment]
Did you read my comment in the other issue. Your config file being ignored is almost certainly solved by by adding ExpandReferenceComments as per - https://github.com/mmanela/chutzpah/wiki/Breaking-change-to-nested-reference-comments-in-version-4.1

**Comment by MrYossu** [comment]
Hello, sorry for the delay in replying, I've been on holiday for a week or so :)

I did read the comment, but didn't realise quite what you meant until you added the explanation here. However, I've added the line, but it doesn't make any difference. If I don't have the refs on the test.js file, the tests all fail, and the web page always pops up.

Here's the full contents of Chutzpah.js...

{
  "References": [
    { "Path": "../KendoMvvm/Scripts/jQuery/jquery-1.10.2.min.js" },
    { "Path": "../KendoMvvm/Scripts/Kendo/kendo.all.min.js" }
  ],
  "ExpandReferenceComments":  "true"
}

Any ideas? Thanks again.

**Comment by PandaWood** [comment]
You'll have to be more careful before giving up - you've put the ExpandReferenceComments in the wrong place - it goes under "Tests"

If you have an editor, like VS Code, it will automatically validate the XML against the public schema for you.

**Comment by MrYossu** [comment]
I did wonder what that Tests bit was doe, but I couldn't see anything in the docs to explain it.

So how should the Json look? I thought all Json was supposed to be enclosed in curly braces, but the snippet on that page didn't. Please can you show me how my Json should be formatted.

Thanks again.

**Comment by MrYossu** [comment]
PandaWood? Anyone? Please can you show me what the whole chutzpah.json file should look like, as I can't work it out from the docs.

However, this still doesn't address the basic issue that I mentioned in my second post, which is that the file seems to be being ignored completely. Even if I had the right code in there, it wouldn't help if the file is being ignored.

**Comment by MrYossu** [comment]
OK, so looking at this again, I think I have the format worked out (see lower down), but it's still not working. As I said in my second post, I think the chutzpah.json file is simply being ignored. Getting the format right is not going to help me until I get that sorted.

Anyone any ideas why the file is being ignored? Here's what I have in there right now...

``{
  "References": [
    { "Path": "../KendoMvvm/Scripts/jQuery/jquery-1.10.2.min.js" },
    { "Path": "../KendoMvvm/Scripts/Kendo/kendo.all.min.js" }
  ],
  "Tests": [
    {
      "Path": "Home",
      "Includes": [ "*.Tests.js" ],
      "ExpandReferenceComments": "true"
    }
  ]
}

**Comment by MrYossu** [comment]
OK, ignore the previous comment. I finally worked it out. I was using the ReSharper Test Explorer (as I do for all unit tests), and when run from there, the chutzpah.json file is ignored.

If I run the tests from the VS Test Explorer window, or by using the context menu in Solution Explorer, it is read fine. It's only when using the R# Test Explorer that it's ignored.

I've opened a [separate issue](https://github.com/mmanela/chutzpah/issues/665) for this, so please ignore this one.

Thanks

**Comment by MrYossu** [comment]
Right, having sorted out why the chutzpah.json file as being ignored (bug in R# v2017.1.2), I am now back to the original question. When I run the unit tests, I get a web page popping up, and I would like to prevent that.

My chutzpah.json file looks like the one I posted on Oct 29, 2017. Any idea why I get the web page?

**Comment by mmanela** [comment]
Is it opening the window only when run from R#?
